version: '3.8'
services:
  vite-react:
    image: node:16.3.0-alpine
    container_name: vite-react
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    ports:
      - ${EXTERNAL_PORT}:${VITE_PORT}
    volumes:
      - '.:/app'
    working_dir: /app
    tty: true
    command: ash -c "yarn install && yarn run dev"
